# Generated by Django 3.2.8 on 2021-10-09 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211009_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='class_took',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
