# Generated by Django 3.2.8 on 2021-10-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_skill_class_took'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
    ]
