# Generated by Django 3.2.8 on 2021-10-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_skill_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='class_took',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
