# Generated by Django 3.2.8 on 2021-10-10 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_skill_class_took'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='class_took',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
