# Generated by Django 3.2.8 on 2021-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_skill_class_took'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='technique',
        ),
        migrations.AlterField(
            model_name='skill',
            name='class_took',
            field=models.CharField(blank=True, default='All', max_length=150, null=True),
        ),
    ]
