# Generated by Django 3.2.8 on 2021-10-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20211010_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='class_took',
        ),
    ]
