# Generated by Django 3.2.8 on 2021-10-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_skill_techniques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='techniques',
            new_name='technique',
        ),
    ]
